tap "cockroachdb/tap"
tap "jaxxstorm/tap"
tap "minio/stable"
tap "oven-sh/bun"
tap "peak/tap"
tap "pulumi/tap"
tap "redpanda-data/tap"
tap "restatedev/tap"
tap "sass/sass"
tap "twitchdev/twitch"
tap "wader/tap"

brew "autoconf"
brew "ccache"
brew "cmake"
brew "coreutils"
brew "direnv"
brew "gettext"
brew "make"
brew "mkcert"

brew "gh"
brew "git"
brew "git-delta"
brew "gitui"
brew "lazygit"

brew "go"
brew "luajit"
brew "python@3.13"
brew "rustup"

brew "oven-sh/bun/bun"
brew "pnpm"

brew "ruff"
brew "uv"

brew "ast-grep"
brew "biome"
brew "scc"
brew "tokei"

brew "atuin"
brew "bat"
brew "choose"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fish"
brew "fzf"
brew "ripgrep"
brew "sd"
brew "tealdeer"
brew "tmux"
brew "zoxide"

brew "bandwhich"
brew "bottom"
brew "btop"
brew "duf"
brew "dust"
brew "gping"
brew "hyperfine"

brew "dive"
brew "helm"
brew "k3d"
brew "kubernetes-cli"
brew "kubectx"
brew "lima"
brew "qemu"

brew "cockroachdb/tap/cockroach"
brew "duckdb"
brew "postgresql@17", restart_service: :changed
brew "redis", restart_service: :changed
brew "sqlite"

brew "cloudflare-wrangler"
brew "cloudflared"
brew "pulumi/tap/pulumi"
brew "terraform"
brew "terragrunt"
brew "vault"

brew "buf"
brew "grex"
brew "jq"
brew "protobuf"
brew "protoc-gen-go"
brew "protoc-gen-go-grpc"
brew "xh"
brew "yq"

brew "caddy"
brew "traefik"

brew "minio/stable/mc"
brew "peak/tap/s5cmd"
brew "rclone"

brew "redpanda-data/tap/redpanda"
brew "temporal"

brew "restatedev/tap/restate"
brew "restatedev/tap/restate-server"

brew "ffmpeg"
brew "hugo"
brew "imagemagick"
brew "pandoc"

brew "capstone"
brew "iperf3"
brew "rustscan"
brew "step"
brew "wireshark"

brew "brotli"
brew "just"
brew "tctl"
brew "twitchdev/twitch/twitch-cli"
brew "unzip"
brew "wget"

brew "neovim"

cask "1password-cli"
cask "clickhouse"
cask "ghostty"
cask "mactex"
cask "orbstack"
cask "osquery"

cask "font-meslo-lg-nerd-font"
cask "font-noto-nerd-font"
cask "font-sauce-code-pro-nerd-font"
